export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const SIGN_UP = 'SIGN_UP';
export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';
export const CHECK_LOGGED_IN = 'IS_LOGGED_IN';

export const SET_LOADING = 'SET_LOADING';

export const GET_LISTS = 'GET_LISTS';
export const GET_LISTS_FAIL = 'GET_LISTS_FAIL';
export const CREATE_LIST = 'CREATE_LIST';
export const CREATE_LIST_FAIL = 'CREATE_LIST_FAIL';
export const UPDATE_LIST = 'UPDATE_LIST';
export const UPDATE_LIST_FAIL = 'UPDATE_LIST_FAIL';
export const DELETE_LIST = 'DELETE_LIST';
export const DELETE_LIST_FAIL = 'DELETE_LIST_FAIL';

export const CREATE_ITEM = 'CREATE_ITEM';
export const CREATE_ITEM_FAIL = 'CREATE_ITEM_FAIL';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const UPDATE_ITEM_FAIL = 'UPDATE_ITEM_FAIL';
export const DELETE_ITEM = 'DELETE_ITEM';
export const DELETE_ITEM_FAIL = 'DELETE_ITEM_FAIL';

export const CREATE_VOCABULARY_ITEM = 'CREATE_VOCABULARY_ITEM';
export const CREATE_VOCABULARY_ITEM_FAIL = 'CREATE_VOCABULARY_ITEM_FAIL';

export const GET_USERS = 'GET_USERS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';

export const CREATE_COLLABS = 'CREATE_COLLABS';
export const CREATE_COLLABS_FAIL = 'CREATE_COLLABS_FAIL';
export const DELETE_COLLAB = 'DELETE_COLLAB';
export const DELETE_COLLAB_FAIL = 'DELETE_COLLAB_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
